config/routes.rb
FundTracker::Application.routes.draw do

  get "series/index" => "series#index", :as => 'series'

  get 'log_in' => "auth#new", :as => 'log_in'
  get 'log_out' => "auth#destroy", :as => 'log_out'
  
  get 'forgot_password' => "auth#forgot_password_form", :as => 'forgot_password_form'
  post 'password_recovery' => "auth#set_password_recovery_hash", :as => 'password_recovery'
  
  get 'reset_password_form/:user_id/:recovery_hash' => "auth#reset_password_form", :as => 'reset_password_form'
  put 'reset_password' => "auth#reset_password", :as => 'reset_password'
  
  root :to => "dashboard#index"
  
  resources :users do 
    get 'edit_profile'
    put 'update_profile'
  end
  
  resources :auth
  resources :companies
  resources :documents
  resources :period_results do
    put :change_period
    put :change_view_type
  end
  resources :operationals do
    put :change_period
  end
  resources :series
  resources :funds
  resources :organizations
  
  resources :companies do
    resources :documents
    resources :series
    resources :period_results do
      get :move_through_time
    end
    resources :user_defined_categories
    resources :operationals do
      get :move_through_time
    end
  end
  
  namespace "admin" do
    resources :organizations do
      resources :funds do
        resources :companies
      end
    end
    resources :companies do
      resources :series
      resources :operationals
      resources :period_results
      resources :forecasts
      resources :user_defined_categories
    end
    
    resources :period_results do
      resources :custom_cells
    end
    
    resources :users do
      get 'edit_profile'
      put 'update_profile'
    end
  end 
  

  

end

app/models/period_result.rb
class PeriodResult < ActiveRecord::Base
  # attr_accessible :bookings, :revenue, :cogs, :operating_expenses, :sg_and_a, :r_and_d, :depreciation, :amortization, :interest_income, :interest_expense, :other_income, :other_expense, :tax_expense, :period, :custom_cells_attributes
  
  validates_presence_of :period, :company_id
  
  belongs_to :company
  has_many :custom_cells
  
  accepts_nested_attributes_for :custom_cells
  
  validates :period, :unique_record => true
  
  def to_s
    self.period.strftime("%m/%Y") unless self.period.nil?
  end
  
  def gross_margin
    ((self.total_revenue - self.total_cogs) / self.total_revenue.to_f) * 100
  end
  
  def gross_profit
    self.total_revenue - self.total_cogs
  end
  
  def total_operating_expenses
    self.operating_expenses + self.sg_and_a + self.r_and_d + total_expense
  end
  
  def operating_profit
    gross_profit - total_operating_expenses
  end
  
  def operating_margin
    operating_profit / self.total_revenue
  end
  
  def net_income
    operating_profit - self.interest_income - self.other_income - self.tax_expense - total_miscellaneous
  end
  
  def net_margin
    (self.net_income / self.total_revenue.to_f) * 100
  end
  
  def total_revenue
    rev = self.revenue ||= 0.0 
    rev += sum_by_category_sign(1,1)  #self.custom_cells.where('user_defined_categories.c_type' => 1, 'user_defined_categories.sign' => 1).includes(:user_defined_category).inject(0.0) { |sum, a| sum + a.amount }
    rev -= sum_by_category_sign(1,2)  #self.custom_cells.where('user_defined_categories.c_type' => 1, 'user_defined_categories.sign' => 2).includes(:user_defined_category).inject(0.0) { |sum, a| sum + a.amount }
  end
  
  def total_cogs
    cogs = self.cogs ||= 0.0
    cogs += sum_by_category_sign(2,1) #self.custom_cells.where('user_defined_categories.c_type' => 2, 'user_defined_categories.sign' => 1).includes(:user_defined_category).inject(0.0) { |sum, a| sum + a.amount }
    cogs -= sum_by_category_sign(2,2) #self.custom_cells.where('user_defined_categories.c_type' => 2, 'user_defined_categories.sign' => 2).includes(:user_defined_category).inject(0.0) { |sum, a| sum + a.amount }
  end
  
  def total_expense
    exp = 0.0
    exp += sum_by_category_sign(3,1) #self.custom_cells.where('user_defined_categories.c_type' => 3, 'user_defined_categories.sign' => 1).includes(:user_defined_category).inject(0.0) { |sum, a| sum + a.amount }
    exp -= sum_by_category_sign(3,2) #self.custom_cells.where('user_defined_categories.c_type' => 3, 'user_defined_categories.sign' => 2).includes(:user_defined_category).inject(0.0) { |sum, a| sum + a.amount }
  end

  def total_miscellaneous
    misc = 0.0
    misc += sum_by_category_sign(4, 1) #self.custom_cells.where('user_defined_categories.c_type' => 4, 'user_defined_categories.sign' => 1).includes(:user_defined_category).inject(0.0) { |sum, a| sum + a.amount }
    misc -= sum_by_category_sign(4, 2) #self.custom_cells.where('user_defined_categories.c_type' => 4, 'user_defined_categories.sign' => 2).includes(:user_defined_category).inject(0.0) { |sum, a| sum + a.amount }
  end
  
private  
  def sum_by_category_sign(c_type, sign)
    self.custom_cells.where('user_defined_categories.c_type' => c_type, 'user_defined_categories.sign' => sign).includes(:user_defined_category).inject(0.0) { |sum, a| sum + a.amount }
  end
end

app/controllers/admin/period_results_controller.rb
class Admin::PeriodResultsController < ApplicationController
  layout 'admin'
  before_filter :is_admin_user, :set_tab_active
  
  def new
    @links = {'Company Edit' => edit_admin_company_path(params[:company_id])}
    @period_result = PeriodResult.new
    @company = Company.find(params[:company_id])
    @revenue, @cogs, @operating_exp, @other = [],[],[],[]
    @company.user_defined_categories.each do |c|
      #@period_result.custom_cells 
      @revenue << CustomCell.new(:user_defined_category_id => c.id, :amount => 0) if c.c_type == 1
      @cogs << CustomCell.new(:user_defined_category_id => c.id, :amount => 0) if c.c_type == 2
      @operating_exp << CustomCell.new(:user_defined_category_id => c.id, :amount => 0) if c.c_type == 3
      @other << CustomCell.new(:user_defined_category_id => c.id, :amount => 0) if c.c_type == 4
    end

    @breadcrumb_trail = "#{@company.fund} > #{@company} > New Financial Data"
  end
  
  def create
    @company = Company.find(params[:company_id])

    @period_result = PeriodResult.new(params[:period_result].merge(:company_id => @company.id))
    @period_result.company_id = @company.id
    
    if @period_result.save
      flash[:notice] = "Financial data added!"
      redirect_to admin_company_period_results_path(@company)
    else
      @links = {'Company Edit' => edit_admin_company_path(@company)}
      @breadcrumb_trail = "#{@company.fund} > #{@company} > New Financial Data"
      render :new
    end
  end

  def edit
    @period_result = PeriodResult.find(params[:id])
    @company = Company.find(params[:company_id])
    @links = {'Company Edit' => edit_admin_company_path(@period_result.company)}
    @breadcrumb_trail = "#{@period_result.company.fund} > #{@period_result.company} > Editing Financial period #{@period_result}"
    @company.user_defined_categories.each do |c|
      @revenue = @period_result.custom_cells.where('user_defined_categories.c_type' => 1).includes('user_defined_category')
      @cogs = @period_result.custom_cells.where('user_defined_categories.c_type' => 2).includes('user_defined_category')
      @operating_exp = @period_result.custom_cells.where('user_defined_categories.c_type' => 3).includes('user_defined_category')
      @other = @period_result.custom_cells.where('user_defined_categories.c_type' => 4).includes('user_defined_category')
    end
  end
  
  def update
    @period_result = PeriodResult.find(params[:id])
    
    if @period_result.update_attributes(params[:period_result])
      flash[:notice] = "Financial period saved!"
      redirect_to admin_company_period_results_path(@period_result.company)
    else
      @links = {'Company Edit' => edit_admin_company_path(@period_result.company)}
      @breadcrumb_trail = "#{@period_result.company.fund} > #{@period_result.company} > Editing Financial period #{@period_result}"
      render :edit
    end
  end

  def index
    @company = Company.find(params[:company_id])
    @links = {'Add Financials' => new_admin_company_period_result_path(@company)}
  end

private
  def set_tab_active
    @funds_class = 'active'
  end
end

app/controllers/period_results_controller.rb
class PeriodResultsController < ApplicationController
  require 'year_summary'
  require 'operational_summary'
  require 'operational_forecast_summary'
  require 'sales_percentage_summary'
  
  before_filter :authenticate_user, :set_tab_active
  
  def new
  end

  def edit
  end

  def index
    @view_by = get_view_by()
    @view_type = get_view_type()
    
    @company = Company.find(params[:company_id])
    @breadcrumb_trail = "PORTFOLIO > #{@company.name.upcase} > FINANCIAL"
    
    case @view_by
    when 'quarter'
      @periods = get_quarters(session[:period])
      @header_row_partial = 'quarterly_header'
    when 'month'
      @periods = get_months(session[:period])
      @header_row_partial = 'monthly_header'
    when 'year'
      @periods = get_years(session[:period])
      @header_row_partial = 'yearly_header'
    end
    
    case @view_type
    when 'forecast'
      @operational_summary = OperationalForecastSummary.new(@periods, @company)
    when 'sales'
      @operational_summary = SalesPercentageSummary.new(@periods, @company)
    else # actuals
      @operational_summary = OperationalSummary.new(@periods, @company)
    end
  end
  
  def change_period
    set_period_type(params[:period_result_id])
    
    redirect_to :action => :index, :company_id => params[:company_id]
  end
  
  def move_through_time
    # based on the  view_by we advance a month, 3 months, or a year
    #params[:id] = 1 for increment 0 for decrement
    crement_period(params[:period_result_id], params[:major])
    
    redirect_to :action => :index, :company_id => params[:company_id]
  end
  
  def change_view_type
    set_view_type(params[:period_result_id])
    
    redirect_to :action => :index, :company_id => params[:company_id]
  end

private
  def set_tab_active
    @portfolio_class = 'active'
    this_year = Date.today.year
    @years = [this_year - 2, this_year - 1, this_year]
  end

end

app/helpers/admin/period_results_helper.rb
module Admin::PeriodResultsHelper
end

app/helpers/period_results_helper.rb
module PeriodResultsHelper

end

#[{"name"=>"Divident Income", "id"=>1, "positive"=>40, "negative"=>0}, {"name"=>"Ca Income", "id"=>3, "positive"=>10000, "negative"=>0}]

app/views/admin/period_results/_form.html.erb
<%= form.error_messages %>
<p>
  <%= form.label :period %><br />
  <%= form.date_select :period, :order => [:month, :year], :include_blank => true %>
</p>
<p>
  <%= form.label :bookings %><br />
  <%= form.text_field :bookings %>
</p>
<span class="bold">Revenue</span>
<p>
  <%= form.label :revenue, "Other Revenue" %><br />
  <%= form.text_field :revenue %>
</p>
<% form.fields_for :custom_cells, @revenue do |builder| %>
	<p>
	  <%= builder.label builder.object.user_defined_category.name %><br />
	  <%= builder.text_field 'amount' %>
		<%= builder.hidden_field 'user_defined_category_id' %>
	</p>
<% end %>
<span class="bold">COGS</span>
<p>
  <%= form.label :cogs %><br />
  <%= form.text_field :cogs %>
</p>
<% form.fields_for :custom_cells, @cogs do |builder| %>
	<p>
	  <%= builder.label builder.object.user_defined_category.name %><br />
	  <%= builder.text_field 'amount' %>
		<%= builder.hidden_field 'user_defined_category_id' %>
	</p>
<% end %>
<span class="bold">Operating Expenses</span>
<p>
  <%= form.label :operating_expenses, 'Other Operating Expenses' %><br />
  <%= form.text_field :operating_expenses %>
</p>
<p>
  <%= form.label :sg_and_a %><br />
  <%= form.text_field :sg_and_a %>
</p>
<p>
  <%= form.label :r_and_d %><br />
  <%= form.text_field :r_and_d %>
</p>
<% form.fields_for :custom_cells, @operating_exp do |builder| %>
	<p>
	  <%= builder.label builder.object.user_defined_category.name %><br />
	  <%= builder.text_field 'amount' %>
		<%= builder.hidden_field 'user_defined_category_id' %>
	</p>
<% end %>
<span class="bold">Other Rev/Exp</span>
<p>
  <%= form.label :depreciation %><br />
  <%= form.text_field :depreciation %>
</p>
<p>
  <%= form.label :amortization %><br />
  <%= form.text_field :amortization %>
</p>
<p>
  <%= form.label :interest_income %><br />
  <%= form.text_field :interest_income %>
</p>
<p>
  <%= form.label :interest_expense %><br />
  <%= form.text_field :interest_expense %>
</p>
<p>
  <%= form.label :other_income %><br />
  <%= form.text_field :other_income %>
</p>
<p>
  <%= form.label :other_expense %><br />
  <%= form.text_field :other_expense %>
</p>	
<p>
  <%= form.label :tax_expense %><br />
  <%= form.text_field :tax_expense %>
</p>
<% form.fields_for :custom_cells, @other do |builder| %>
	<p>
	  <%= builder.label builder.object.user_defined_category.name %><br />
	  <%= builder.text_field 'amount' %>
		<%= builder.hidden_field 'user_defined_category_id' %>
	</p>
<% end %>
<p>
	<%= form.submit :save %>
</p>

app/views/admin/period_results/edit.html.erb
<%= form_for @period_result, :url => admin_company_period_result_path(@period_result) do |f| -%>
  <%= render :partial => 'form', :object => f %>
<% end -%>

app/views/admin/period_results/index.html.erb
<h1>Financial data for <%= @company %></h1>
<% @breadcrumb_trail = raw("#{link_to(@company, edit_admin_fund_company_path(@company.fund,@company))} > Financial data") %>

<table id="company_period_results_table">
	<% @company.period_results.each do |p| %>
		<tr class="<%= cycle('even', 'odd') %>">
			<td><%= p %></td>
			<td><%= link_to "edit", edit_admin_company_period_result_path(@company, p) %></td>
		</tr>
	<% end %>
</table>

app/views/admin/period_results/new.html.erb
<%= form_for @period_result, :url => admin_company_period_results_path(@company) do |f| -%>
  <%= render :partial => 'form', :object => f %>
<% end -%>