config/routes.rb
FundTracker::Application.routes.draw do

  get "series/index" => "series#index", :as => 'series'

  get 'log_in' => "auth#new", :as => 'log_in'
  get 'log_out' => "auth#destroy", :as => 'log_out'
  
  get 'forgot_password' => "auth#forgot_password_form", :as => 'forgot_password_form'
  post 'password_recovery' => "auth#set_password_recovery_hash", :as => 'password_recovery'
  
  get 'reset_password_form/:user_id/:recovery_hash' => "auth#reset_password_form", :as => 'reset_password_form'
  put 'reset_password' => "auth#reset_password", :as => 'reset_password'
  
  root :to => "dashboard#index"
  
  resources :users do 
    get 'edit_profile'
    put 'update_profile'
  end
  
  resources :auth
  resources :companies
  resources :documents
  resources :period_results do
    put :change_period
    put :change_view_type
  end
  resources :operationals do
    put :change_period
  end
  resources :series
  resources :funds
  resources :organizations
  
  resources :companies do
    resources :documents
    resources :series
    resources :period_results do
      get :move_through_time
    end
    resources :user_defined_categories
    resources :operationals do
      get :move_through_time
    end
  end
  
  namespace "admin" do
    resources :organizations do
      resources :funds do
        resources :companies
      end
    end
    resources :companies do
      resources :series
      resources :operationals
      resources :period_results
      resources :forecasts
      resources :user_defined_categories
    end
    
    resources :period_results do
      resources :custom_cells
    end
    
    resources :users do
      get 'edit_profile'
      put 'update_profile'
    end
  end 
  

  

end

app/models/company.rb
class Company < ActiveRecord::Base
  # attr_accessible :fund_id, :name, :founded, :industry_id, :description, :reserves, :syndicate, :status_id, :status_date, :exit_amount, :fund_return, :notes, :active
  
  validates_presence_of :fund_id, :name, :industry_id
  
  belongs_to :fund
  has_many :series, :order => 'date desc'
  has_many :operationals, :order => 'period_end desc'
  has_many :period_results
  has_many :users
  has_many :documents
  has_many :folders
  has_many :user_defined_categories
  has_many :forecasts, :order => 'period asc'
  
  before_save :clear_status_date
  
  scope :active, where(:active => true)
  
  STATUS = {1 => 'Active', 2 => 'Exited', 3 => 'Write-off'}

  def to_s
    name
  end
  
  def investment_total
    self.series.inject(0.0) { |sum, s|  sum += s.investment }
  end
  
  def most_recent_series
    self.series.first.name.gsub(/Series/,'')
  rescue
    ''
  end
  
  def current_head_count
    self.operationals.first.head_count
  rescue
    0
  end
  
  def self.options_for_select
    self.active.map { |c| [c.name, c.id] }
  end
  
  def ttm_revenue
    # revenue from the past 12 months -- financials
    e = Date.today.end_of_month
    s = e.months_ago(12).beginning_of_month
    ttm = self.period_results.sum(:revenue, :conditions => ['period between ? AND ?', s, e])
  end
  
  def cash_runway
    self.operationals.first.cash_balance / self.operationals.first.cash_burn
  rescue
    0
  end
  
  def ownership_percentage
    self.series.first.fully_diluted_ownership
  rescue
    0
  end
  
private

  def clear_status_date
    # clear status date if not active
    if self.status_id == 1
      self.status_date = nil
    end
  end
end

app/controllers/admin/companies_controller.rb
class Admin::CompaniesController < ApplicationController
  require 'year_summary'
  require 'operational_summary'

  layout 'admin'
  before_filter :is_admin_user, :set_tab_active
  
  def new
    @organization = Organization.find(params[:organization_id])
    @fund = @organization.funds.find(params[:fund_id])
    @company = @fund.companies.build
    @breadcrumb_trail = "#{@fund} > New Company"
  end

  def show
    @organization = Organization.find(params[:organization_id])
    @fund = @organization.funds.find(params[:fund_id])
    @company = @fund.companies.find(params[:id])
    session[:company_id] = params[:id]
    session[:fund_id] = @fund.id
    @periods = get_years(session[:period])
    @operational_summary = OperationalSummary.new(@periods, @company)
  end
  
  def create
    @organization = Organization.find(params[:organization_id])
    @fund = @organization.funds.find(params[:fund_id])
    @company = @fund.companies.build(params[:company])
    
    if @company.save
      flash[:notice] = "Company added!"
      redirect_to admin_organization_fund_path(@organization, @fund)
    else
      render new_admin_organization_fund_company_path(@organization, @fund)
    end
  end
  
  def index
    if session[:fund_id].present?
      @fund = Fund.find(session[:fund_id])
      @organization = @fund.organization
      @companies = @fund.companies
    else
      @organization = Organization.find(session[:organization_id])
      @companies = @organization.companies
    end
  end

  def edit
    @organization = Organization.find(params[:organization_id])
    @fund = @organization.funds.find(params[:fund_id])
    @company = @fund.companies.find(params[:id])
    @links = {'Edit ' + @company.fund.to_s => edit_admin_organization_fund_path(@company.fund)}
  end

  def update
    @organization = Organization.find(params[:organization_id])
    @fund = @organization.funds.find(params[:fund_id])
    @company = @fund.companies.find(params[:id])
    
    if @company.update_attributes(params[:company])
      flash[:notice] = "Company saved!"
      redirect_to admin_organization_fund_company_path(@organization, @fund, @company)
    else
      render :edit
    end
  end

private
  def set_tab_active
    @funds_class = 'active'
    # @links = {'Fund List' => admin_organization_funds_path}
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  require 'year_summary'
  before_filter :authenticate_user, :set_tab_active
  
  def index
    @companies = current_user.company_array
    @breadcrumb_trail = "PORTFOLIO > SUMMARY"
    @company_sub_nav_style = 'display: none;'
  end

  def new
  end

  def edit
  end
  
  def show
    @company = Company.find(params[:id])
    @year1 = YearSummary.new(@company, Date.today.year)
    @year2 = YearSummary.new(@company, Date.today.year - 1)
    @year3 = YearSummary.new(@company, Date.today.year - 2)
    @precision = 0
    @breadcrumb_trail = "PORTFOLIO > #{@company.name.upcase} > FINANCIAL"
  end

private
  def set_tab_active
    @portfolio_class = 'active'
  end
end

app/helpers/admin/companies_helper.rb
module Admin::CompaniesHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/admin/companies/_form.html.erb
<%= form.error_messages %>
<p>
  <%= form.label :name %><br />
  <%= form.text_field :name %>
</p>
<p>
  <%= form.label :founded %><br />
  <%= form.date_select :founded, :order => [:month, :day, :year] %>
</p>
<p>
  <%= form.label :industry_id %><br />
  <%= form.select :industry_id, [['technology', 1]], :include_blank => true %>
</p>
<p>
  <%= form.label :description %><br />
  <%= form.text_area :description, :size => '60x5' %>
</p>
<p>
  <%= form.label :reserves %><br />
  <%= form.text_field :reserves %>
</p>
<p>
  <%= form.label :syndicate %><br />
  <%= form.text_area :syndicate, :size => '60x5' %>
</p>
<p>
  <%= form.label :status_id %><br />
  <%= form.select :status_id, Company::STATUS.invert.to_a.sort, {:include_blank => true}, :onchange => "exit_date(this)" %>
</p>

<div style="display: none;" id="exit_date_p">
	<p>
	  <%= form.label :status_date, "Exit date" %><br />
	  <%= form.date_select :status_date, :order => [:month, :day, :year], :include_blank => true %>
	</p>
	<p>
	  <%= form.label :exit_amount %><br />
	  <%= form.text_field :exit_amount %>
	</p>
</div>

<p>
  <%= form.label :fund_return %><br />
  <%= form.text_field :fund_return %>
</p>
<p>
  <%= form.label :notes %><br />
  <%= form.text_area :notes, :size => '60x6' %>
</p>
<p>
  <%= form.label :active %><br />
  <%= form.check_box :active %>
</p>
<p>
	<%= form.submit :save %>
</p>
<script type="text/javascript" charset="utf-8">
	$(document).ready(function () {
		exit_date($('#company_status_id').get(0));
	});
	
	function exit_date(select) {
		if (select.value == 1 || select.value == '') {
			$('#exit_date_p').hide();
		} else {
			$('#exit_date_p').show();
		};
	}
</script>

app/views/admin/companies/edit.html.erb
<% @breadcrumb_trail = raw("#{link_to(@company.fund, edit_admin_organization_fund_path(@company.fund))} > Editing #{@company}") %>
<div id="edit_company">
	<%= form_for @company, :url => admin_organization_fund_company_path(@organization, @fund, @company) do |f| -%>
		<%= render :partial => 'form', :object => f %>
	<% end -%>
</div>

<br />
<%= link_to 'Back', admin_organization_fund_company_path(@organization, @fund, @company)%>

app/views/admin/companies/index.html.erb
<h2>Companies</h2>
<table style="width:1000px">
	<tr class="left" style="border-bottom:1px solid">
		<th class="column_width">Company</th>
		<th class="column_width">Ownership %</th>
		<th class="column_width">TTM Revenue</th>
		<th class="column_width">TTM Revenue Growth %</th>
		<th class="column_width">Rev/Employee</th>
		<th class="column_width">Exp/Employee</th>
		<th class="column_width">Cash Runway</th>
	</tr>
	<% @companies.each do |company| %>
	<tr class="<%= cycle('odd','even') %>">
		<td><%= link_to company.name, admin_company_path(company) %></td>
		<td class="right"><%= ph(company.ownership_percentage) %></td>
		<td class="right"><%= nh(company.ttm_revenue) %></td>
		<td class="right"><%= %></td>
		<td class="right"><%= %></td>
		<td class="right"><%= %></td>
		<td class="right"><%= nh(company.cash_runway) %></td>
	</tr>
	<% end %>
</table>

app/views/admin/companies/new.html.erb
<%= form_for [@organization, @fund, @company], :url => admin_organization_fund_companies_path do |f| -%>
	<%= render :partial => 'form', :object => f %>
<% end -%>

app/views/admin/companies/show.html.erb
<h2><%= @company.name %></h2>

<div id="company_summary_container">

	<div id="company_summary_box">
		<div id="company_summary_box_title">Investment Detail</div>
		<div id="company_summary_box_content_container">
			<div id="company_summary_box_content_name">Ownership</div>	
			<div id="company_summary_box_content_value">14.5%</div>
		</div>
		<div id="company_summary_box_content_container">
			<div id="company_summary_box_content_name">Our Total Investment</div>	
			<div id="company_summary_box_content_value">$2,000,000</div>
		</div>
		<div id="company_summary_box_content_container">
			<div id="company_summary_box_content_name">First Investment</div>	
			<div id="company_summary_box_content_value">Jan 20, 2009</div>
		</div>		
		<div id="company_summary_box_content_container">
			<div id="company_summary_box_content_name">Most Recent Series</div>	
			<div id="company_summary_box_content_value">Series A</div>
		</div>
		<div id="company_summary_box_content_container">
			<div id="company_summary_box_content_name">Total Capital Raised (to date)</div>	
			<div id="company_summary_box_content_value">$6,000,000</div>
		</div>
		<div id="company_summary_box_content_container">
			<div id="company_summary_box_content_name">Initial Pre / Current Post</div>	
			<div id="company_summary_box_content_value">$2M / $15M</div>
		</div>
	</div>

	<div id="company_summary_box">
		<div id="company_summary_box_title">Operational Metrics</div>
		<div id="company_summary_box_content_container">
			<div id="company_summary_box_content_name">TTM Monthly Revenue Growth</div>	
			<div id="company_summary_box_content_value">10.0%</div>
		</div>
		<div id="company_summary_box_content_container">
			<div id="company_summary_box_content_name">Cash Balance</div>	
			<div id="company_summary_box_content_value">$2,000,000</div>
		</div>
		<div id="company_summary_box_content_container">
			<div id="company_summary_box_content_name">Cash Burn (monthly)</div>	
			<div id="company_summary_box_content_value">$200,000</div>
		</div>		
		<div id="company_summary_box_content_container">
			<div id="company_summary_box_content_name">Cash Runway</div>	
			<div id="company_summary_box_content_value">10 months</div>
		</div>
		<div id="company_summary_box_content_container">
			<div id="company_summary_box_content_name">Revenue per employee (annual)</div>	
			<div id="company_summary_box_content_value">$40,000</div>
		</div>
		<div id="company_summary_box_content_container">
			<div id="company_summary_box_content_name">Expense per revenue (annual)</div>	
			<div id="company_summary_box_content_value">$50,000</div>
		</div>
	</div>

	<div id="company_summary_box_tall">
		<div id="company_summary_box_tall_title"><%= @company.name %> | Investment Summary</div>
		<div id="company_summary_box_tall_content_container">
			<div id="company_summary_box_tall_content_name">Description</div>	
			<div id="company_summary_box_tall_content_value"><%= @company.description %></div>
		</div>
		<div id="company_summary_box_tall_content_container">
			<div id="company_summary_box_tall_content_name">Industry</div>	
			<div id="company_summary_box_tall_content_value"><%= @company.industry_id %></div>
		</div>
		<div id="company_summary_box_tall_content_container">
			<div id="company_summary_box_tall_content_name">Employees</div>	
			<div id="company_summary_box_tall_content_value">34</div>
		</div>		
		<div id="company_summary_box_tall_content_container">
			<div id="company_summary_box_tall_content_name">Founded</div>	
			<div id="company_summary_box_tall_content_value"><%= @company.founded %></div>
		</div>
		<div id="company_summary_box_tall_content_container">
			<div id="company_summary_box_tall_content_name">Syndicate</div>	
			<div id="company_summary_box_tall_content_value">Benchmark Capital, Columbia Capital</div>
		</div>
		<div id="company_summary_box_tall_content_container">
			<div id="company_summary_box_tall_content_name">Partner</div>	
			<div id="company_summary_box_tall_content_value">Phil Reed</div>
		</div>
		<div id="company_summary_box_tall_content_container">
			<div id="company_summary_box_tall_content_name">Sourced</div>	
			<div id="company_summary_box_tall_content_value">Village Network</div>
		</div>
		<div id="company_summary_box_tall_content_container">
			<div id="company_summary_box_tall_content_name">Stage</div>	
			<div id="company_summary_box_tall_content_value">Early</div>
		</div>
	</div>
			
	<div id="company_summary_box_wide">
		<div id="company_summary_box_wide_title">Income Statement</div>
		<div id="company_summary_box_wide_content_container">
			<div id="company_summary_box_wide_content_name">Year</div>	
			<div id="company_summary_box_wide_content_value">2009</div>
			<div id="company_summary_box_wide_content_value">2010</div>
			<div id="company_summary_box_wide_content_value">2011</div>
		</div>
		<div id="company_summary_box_wide_content_container">
			<div id="company_summary_box_wide_content_name">Bookings</div>	
			<div id="company_summary_box_wide_content_value">$3,000,000</div>
			<div id="company_summary_box_wide_content_value">$5,000,000</div>
			<div id="company_summary_box_wide_content_value">$7,000,000</div>			
		</div>
		<div id="company_summary_box_wide_content_container">
			<div id="company_summary_box_wide_content_name">Revenue</div>	
			<div id="company_summary_box_wide_content_value">$2,000,000</div>
			<div id="company_summary_box_wide_content_value">$3,000,000</div>
			<div id="company_summary_box_wide_content_value">$4,000,000</div>
		</div>
		<div id="company_summary_box_wide_content_container">
			<div id="company_summary_box_wide_content_name">Compound annual growth rate</div>	
			<div id="company_summary_box_wide_content_value">13.5%</div>
			<div id="company_summary_box_wide_content_value">10.5%</div>
			<div id="company_summary_box_wide_content_value">9.0%%</div>
		</div>		
		<div id="company_summary_box_wide_content_container">
			<div id="company_summary_box_wide_content_name">Gross Margin</div>	
			<div id="company_summary_box_wide_content_value">67.4%</div>
			<div id="company_summary_box_wide_content_value">70.0%</div>
			<div id="company_summary_box_wide_content_value">68.7%</div>
		</div>
		<div id="company_summary_box_wide_content_container">
			<div id="company_summary_box_wide_content_name">Operating Margin</div>	
			<div id="company_summary_box_wide_content_value">34.7%</div>
			<div id="company_summary_box_wide_content_value">40.0%</div>
			<div id="company_summary_box_wide_content_value">41.0%</div>
		</div>
		<div id="company_summary_box_wide_content_container">
			<div id="company_summary_box_wide_content_name">Net Margin</div>	
			<div id="company_summary_box_wide_content_value">12.3%</div>
			<div id="company_summary_box_wide_content_value">15.0%</div>
			<div id="company_summary_box_wide_content_value">13.0%</div>
		</div>
	</div>

</div>

<table style="width:600px">
  <tr>
    <td>Year</td>
    <% @operational_summary.period_set.each do |ps| %>
      <td><%= ps.year %></td>
    <% end %>
  </tr>
  <tr>
    <td>Bookings</td>
    <% @operational_summary.period_set.each do |ps| %>
      <td><%= nh(ps.revenue) %></td>
    <% end %>
  </tr>
  <tr>
    <td>Revenue</td>
    <% @operational_summary.period_set.each do |ps| %>
      <td><%= nh(ps.revenue) %></td>
    <% end %>
  </tr>
</table>


<br />
<div class='back_footer'>
	<%= link_to 'Edit', edit_admin_organization_fund_company_path(@organization, @fund)%> | 
	<%= link_to 'Back', admin_organization_fund_path(@organization, @fund) %>
</div>