config/routes.rb
FundTracker::Application.routes.draw do

  get "series/index" => "series#index", :as => 'series'

  get 'log_in' => "auth#new", :as => 'log_in'
  get 'log_out' => "auth#destroy", :as => 'log_out'
  
  get 'forgot_password' => "auth#forgot_password_form", :as => 'forgot_password_form'
  post 'password_recovery' => "auth#set_password_recovery_hash", :as => 'password_recovery'
  
  get 'reset_password_form/:user_id/:recovery_hash' => "auth#reset_password_form", :as => 'reset_password_form'
  put 'reset_password' => "auth#reset_password", :as => 'reset_password'
  
  root :to => "dashboard#index"
  
  resources :users do 
    get 'edit_profile'
    put 'update_profile'
  end
  
  resources :auth
  resources :companies
  resources :documents
  resources :period_results do
    put :change_period
    put :change_view_type
  end
  resources :operationals do
    put :change_period
  end
  resources :series
  resources :funds
  resources :organizations
  
  resources :companies do
    resources :documents
    resources :series
    resources :period_results do
      get :move_through_time
    end
    resources :user_defined_categories
    resources :operationals do
      get :move_through_time
    end
  end
  
  namespace "admin" do
    resources :organizations do
      resources :funds do
        resources :companies
      end
    end
    resources :companies do
      resources :series
      resources :operationals
      resources :period_results
      resources :forecasts
      resources :user_defined_categories
    end
    
    resources :period_results do
      resources :custom_cells
    end
    
    resources :users do
      get 'edit_profile'
      put 'update_profile'
    end
  end 
  

  

end

app/models/organization.rb
class Organization < ActiveRecord::Base
  validates_presence_of :name
  
  has_many :funds
  has_many :companies, :through => :funds

end

app/controllers/admin/organizations_controller.rb
class Admin::OrganizationsController < ApplicationController

  before_filter :set_tab_active

  layout 'admin'
  # before_filter :is_admin_user, :set_tab_active

  def index
    @organizations = Organization.all
    reset_organization_session
    @organization = nil
    @fund = nil
  end
  
  def show
    @organization = Organization.find(params[:id])
    session[:organization_id] = @organization.id
    reset_fund_session
    @funds = @organization.funds.order('start_date ASC')
    @fund = @organization
  end

  def new
    @organization = Organization.new
  end
  
  def create
    @organization = Organization.new(params[:organization])
    
    if @organization.save
      redirect_to admin_organizations_path
    else
      render :new
    end
  end

  def edit
    @organization = Organization.find(params[:id])
  end
  
  def update
    @organization = Organization.find(params[:id])
    
    if @organization.update_attributes(params[:organization])
      flash[:notice] = "Organization saved!"
      redirect_to edit_admin_organization_path(@organization)
    else
      render :edit
    end
  end
  
  def destroy
    @organization = Organization.find(params[:id])
    
    @organization.destroy
    
    redirect_to admin_organizations_path
  end 

private
  def set_tab_active
    @organizations_class = 'active'
  end
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController

end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/views/admin/organizations/_form.html.erb
<%= form_for @organization do |f| %>

<p>  
  <%= f.label :name %>
  <%= f.text_field :name %>
</p>

<p>
  <%= f.submit %>
</p>

<% end %>

app/views/admin/organizations/edit.html.erb
<h2>Edit Organization</h2>

<%= form_for @organization, :url => admin_organization_path do |f| -%>
  <%= render 'form', :object => f %>
<% end -%>

<div class="back_footer">
  <%= link_to 'Back', admin_organizations_path %>
</div>

app/views/admin/organizations/index.html.erb
<table style="text-align:left;width:500px">
	<tr>
		<th>Organization</th>
		<th>Funds</th>
		<th>Companies</th>
    <th></th>
	</tr>
	<% @organizations.each do |organization| %>
	<tr>
		<td><%= link_to organization.name, admin_organization_path(organization) %></td>
		<td><%= organization.funds.count %></td>
		<td><%= organization.companies.count %></td>
    <td><%= link_to 'Edit', edit_admin_organization_path(organization) %> | 
        <%= link_to 'Destroy', admin_organization_path(organization), :confirm => 'Are you sure?', :method => :delete %></td>
	</tr>
	<% end %>
</table>

<div class='back_footer'>
	<%= link_to 'Add Organization', new_admin_organization_path %>
</div>

app/views/admin/organizations/new.html.erb
<h2>New Organization</h2>
<%= form_for @organization, :url => admin_organizations_path do |f| -%>
  <%= render 'form', :object => f %>
<% end -%>

<div class="back_footer">
  <%= link_to 'Back', admin_organizations_path %>
</div>

app/views/admin/organizations/show.html.erb
<h4>
	<%= "#{@organization.name} | Total Funds: #{@funds.count}"%>
</h4>
<br />

<table class="org_summary">
	<tr>
		<th>Fund</th>
		<th>Total Companies</th>
		<th>Total Size</th>
		<th>Mgmt Fee <br />Estimate</th>
		<th>Invested <br />to date</th>
		<th>Reserves</th>
		<th>Remaining Investible</th>
		<th>As % of <br />Total Size</th>
		<th>Close Date</th>
	</tr>
	<% @funds.each do |fund| %>
	<tr>
		<td><%= link_to "Fund #{fund.number}", admin_organization_fund_path(@organization, fund) %></td>
		<td class="center"><%= fund.companies.size %></td>
		<td class="right"><%= nh(fund.size) %></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
	</tr>
	<% end %>
</table>

<table class="org_summary top_space">
	<th>All Companies</th>
	<th>Owership %</th>
	<th>Our Total<br />Investment</th>
	<th>TTM Revenue</th>
	<th>TTM Monthly<br />Rev Growth</th>
	<th>Rev/Employee</th>
	<th>Exp/Employee</th>
	<th>Cash Runway</th>
	<th>Fund</th>
	<% @organization.companies.each do |c| %>
		<tr>
			<td><%= link_to c.name, admin_organization_fund_company_path(@organization, c.fund, c) %></td>
			<td class="right"><%= ph(c.ownership_percentage) %></td>
			<td class="right"><%= nh(c.investment_total) %></td>
			<td class="right"><%= nh(c.ttm_revenue) %></td>
			<td></td>
			<td></td>
			<td></td>
			<td class="right"><%= c.cash_runway %></td>
			<td></td>
		</tr>
	<% end %>
</table>

<br />
<div class='back_footer'>
	<%= link_to 'Add Fund', new_admin_organization_fund_path(@organization,@fund) %> | 
	<%= link_to 'Back', admin_organizations_path %>
</div>