config/routes.rb
FundTracker::Application.routes.draw do

  get "series/index" => "series#index", :as => 'series'

  get 'log_in' => "auth#new", :as => 'log_in'
  get 'log_out' => "auth#destroy", :as => 'log_out'
  
  get 'forgot_password' => "auth#forgot_password_form", :as => 'forgot_password_form'
  post 'password_recovery' => "auth#set_password_recovery_hash", :as => 'password_recovery'
  
  get 'reset_password_form/:user_id/:recovery_hash' => "auth#reset_password_form", :as => 'reset_password_form'
  put 'reset_password' => "auth#reset_password", :as => 'reset_password'
  
  root :to => "dashboard#index"
  
  resources :users do 
    get 'edit_profile'
    put 'update_profile'
  end
  
  resources :auth
  resources :companies
  resources :documents
  resources :period_results do
    put :change_period
    put :change_view_type
  end
  resources :operationals do
    put :change_period
  end
  resources :series
  resources :funds
  resources :organizations
  
  resources :companies do
    resources :documents
    resources :series
    resources :period_results do
      get :move_through_time
    end
    resources :user_defined_categories
    resources :operationals do
      get :move_through_time
    end
  end
  
  namespace "admin" do
    resources :organizations do
      resources :funds do
        resources :companies
      end
    end
    resources :companies do
      resources :series
      resources :operationals
      resources :period_results
      resources :forecasts
      resources :user_defined_categories
    end
    
    resources :period_results do
      resources :custom_cells
    end
    
    resources :users do
      get 'edit_profile'
      put 'update_profile'
    end
  end 
  

  

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :password
  before_save :encrypt_password, :clear_company
  
  attr_accessible :first_name, :last_name, :email, :password, :active, :fund_id, :role_id, :company_id
  
  belongs_to :fund
  belongs_to :company
  
  validates_presence_of :email, :first_name, :last_name
  validates_presence_of :password, :on => :create, :message => "can't be blank"
  validates_uniqueness_of :email
  validates_confirmation_of :password
  validates_length_of :password, :within => 8..20, :allow_blank => true
  validates_presence_of :fund_id, :if => Proc.new { |u| u.is_admin == false && [1,2].include?(u.role_id) }
  validates_presence_of :role_id, :if => Proc.new { |u| u.is_admin == false }
  validates_presence_of :company_id, :if => Proc.new { |u| u.role_id == 3 }
  
  scope :active, where(:active => true)
  
  ROLES = { 1 => 'Fund Administrator', 2 => 'Fund User', 3 => 'Company User' }
    
  def encrypt_password
    if password.present?
      self.password_hash = BCrypt::Password.create(password)
    end
  end
  
  def clear_company
    # if the user role is not company user then no need for a company id
    if self.role_id != 3
      self.company_id = nil
    end
  end
  
  def to_s
    [first_name, last_name].join(' ')
  end
  
  def self.find_active_user(id)
    raise if id.nil?
    self.where(:active => true, :id => id).first
  end
  
  def show_role
    if self.is_admin?
      '<span title="Application Administrator">AA</span>'
    else
      case self.role_id
        when 1 then '<span title="Fund Administrator">FA</span>'
        when 2 then '<span title="Fund User">FU</span>'
        when 3 then '<span title="Company User">CU</span>'
      end
    end
  end
  
  def clear_recovery_params
    self.password_recovery_hash = nil
    self.recovery_hash_created_at = nil
    self.save
  end
  
  def _password
    BCrypt::Password.new(password_hash)
  rescue 
    ''
  end
  
  def company_array
    if self.fund_id.nil?
      self.company.to_a
    else
      self.fund.companies.all
    end
  end
  
private
  
  def self.authenticate(email, password)
    user = self.find_by_email(email)
    if user && user._password == password
      user.update_attribute(:last_login, Time.now)
      user
    else
      nil
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  layout 'admin'
  before_filter :is_admin_user, :set_tab_active
  
  def index
    @links = {'Add User' => new_admin_user_path}
    @users = User.all
    @breadcrumb_trail = "User List"
  end
  
  def new
    # if there are no funds we need to let them know to set up
    # a fund before adding users
    if Fund.all.size > 0
      @links = {'User List' => admin_users_path}
      @user = User.new
      @breadcrumb_trail = "Adding a User"
    else
      flash[:alert] = "A fund must be created before users can be added."
      redirect_to new_admin_fund_path
    end
  end
  
  def create
    @user = User.new(params[:user])
    
    if @user.save 
      flash[:notice] = "User successfully created..."
      redirect_to admin_users_path
    else
      @links = {'User List' => admin_users_path}
      render :new
    end
  end
  
  def edit
    @links = {'User List' => admin_users_path}
    @user = User.find(params[:id])
    @breadcrumb_trail = "Editing #{@user}"
  end
  
  def update
    @user = User.find(params[:id])
    
    if @user.update_attributes(params[:user])
      flash[:notice] = "User updated"
      redirect_to admin_users_path
    else
      @links = {'User List' => admin_users_path}
      render :edit
    end
  end
  
  def edit_profile
    @links = {'User List' => admin_users_path}
    @user = User.find(params[:user_id])
    @breadcrumb_trail = "Editing profile for #{@user}"
    if params[:user_id].to_i != session[:user_id]
      flash[:alert] = "You are not allowed to edit the profile of someone else"
      redirect_to admin_users_path
    end
  end
  
  def update_profile
    
    @user = User.find(params[:user_id])
    
    unless params[:password].empty?
      @user.password = params[:password]
      @user.password_confirmation = params[:password_confirmation]
    end
    
    if @user.update_attributes(params[:user])
      flash[:notice] = "Profile updated"
      redirect_to admin_users_path
    else
      @links = {'User List' => admin_users_path}
      render :edit_profile
    end
  end
  
private
  def set_tab_active
    if ['edit_profile', 'update_profile'].include?(action_name)
      @profile_class = 'active'
    else
      @users_class = 'active'
    end 
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user, :set_tab_active

  def index
    @links = {'Add User' => new_admin_user_path}
    @users = current_user.fund.users + current_user.fund.company_users
    @breadcrumb_trail = "User List"
  end
  
  def new
    @user = User.new
  end
  
  def create
    # validate company
    # generate password and maybe email it to the user
    @user = User.new(params[:user])
    @user.password = generate_password
    puts "**********" + @user.password + "**********"
        
    if @user.save 
      flash[:notice] = "User successfully created..."
      redirect_to users_path
    else
      @links = {'User List' => users_path}
      render :new
    end
  end
  
  def update
    @user = User.find(params[:id])
    
    if @user.update_attributes(params[:user])
      flash[:notice] = "User updated"
      redirect_to users_path
    else
      @links = {'User List' => users_path}
      render :edit
    end
  end
  
  def edit
    @links = {'User List' => users_path}
    @user = User.find(params[:id])
    @breadcrumb_trail = "Editing #{@user}"
  end
  
  def edit_profile
    @links = {'User List' => users_path}
    @user = User.find(params[:user_id])
    @breadcrumb_trail = "Editing profile for #{@user}"
    if params[:user_id].to_i != session[:user_id]
      flash[:alert] = "You are not allowed to edit the profile of someone else"
      redirect_to users_path
    end
  end
  
  def update_profile
    @user = User.find(params[:user_id])
    
    unless params[:password].empty?
      @user.password = params[:password]
      @user.password_confirmation = params[:password_confirmation]
    end
    
    if @user.update_attributes(params[:user])
      flash[:notice] = "Profile updated"
      redirect_to users_path
    else
      @links = {'User List' => users_path}
      render :edit_profile
    end
  end
  
private
  def set_tab_active
    if ['edit_profile', 'update_profile'].include?(action_name)
      @profile_class = 'active'
    else
      @users_class = 'active'
    end 
  end  
  
  def generate_password
    source_characters = "0a1b2c4d3e5f6g7h8i9jklmnopqrstuvwxyz" 
    password = "" 
    1.upto(8) { password += source_characters[rand(source_characters.length),1] }
    return password
  end
  
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper

  def boolean_icon(b)
    if b
      image_tag('accept.png')
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.erb
<%= form.error_messages %>

<p>
  <%= form.label :email %><br />
  <%= form.text_field :email, :size => 45 %>
</p>

<p>
  <%= form.label :first_name %><br />
  <%= form.text_field :first_name %>
</p>

<p>
  <%= form.label :last_name %><br />
  <%= form.text_field :last_name %>
</p>

<p>
  <%= form.label :password %><br />
  <%= form.password_field :password %>
</p>

<p>
  <%= form.label :password_confirmation %><br />
  <%= form.password_field :password_confirmation %>
</p>

<% unless @user.is_admin? %>
	<p>
	  <%= form.label :fund_id %><br />
	  <%= form.select :fund_id, Fund.options_for_select, :include_blank => true %>
	</p>
	<p>
	  <%= form.label :role_id %><br />
	  <%= form.select :role_id, User::ROLES.invert.to_a.sort, :include_blank => true %>
	</p>
<% end %>

<p>
  <%= form.label :active %><br />
  <%= form.check_box :active %>
</p>

<p>
	<%= form.submit 'Save' %>
</p>

app/views/admin/users/edit.html.erb
<%= form_for @user, :url => admin_user_path(@user) do |form| -%>
	<%= form.error_messages %>

	<p>
	  <%= form.label :email %><br />
	  <%= form.text_field :email, :size => 45 %>
	</p>

	<p>
	  <%= form.label :first_name %><br />
	  <%= form.text_field :first_name %>
	</p>

	<p>
	  <%= form.label :last_name %><br />
	  <%= form.text_field :last_name %>
	</p>
	
	<% unless @user.is_admin? %>
		<p>
		  <%= form.label :fund_id %><br />
		  <%= form.select :fund_id, Fund.options_for_select, :include_blank => true %>
		</p>
		<p>
		  <%= form.label :role_id %><br />
		  <%= form.select :role_id, User::ROLES.invert.to_a.sort, :include_blank => true %>
		</p>
	<% end %>

	<p>
	  <%= form.label :active %><br />
	  <%= form.check_box :active %>
	</p>

	<p>
		<%= form.submit 'Save' %>
	</p>
<% end -%>

app/views/admin/users/edit_profile.html.erb
<%= form_for @user, :url => admin_user_update_profile_path(@user) do |form| -%>
	<%= form.error_messages %>

	<p>
	  <%= form.label :email %><br />
	  <%= form.text_field :email, :size => 45 %>
	</p>

	<p>
	  <%= form.label :first_name %><br />
	  <%= form.text_field :first_name %>
	</p>

	<p>
	  <%= form.label :last_name %><br />
	  <%= form.text_field :last_name %>
	</p>
	
	<p>
	  <%= form.label :password %><br />
	  <%= password_field_tag :password, nil, :size => 20 %>
	</p>

	<p>
	  <%= form.label :password_confirmation %><br />
	  <%= password_field_tag :password_confirmation, nil, :size => 20 %>
	</p>

	<p>
		<%= form.submit 'Save' %>
	</p>
<% end -%>

app/views/admin/users/index.html.erb
<table>
	<tr>
		<th class="left">User</th>
		<th>Email</th>
		<th class="left">Fund</th>
		<th>Role</th>
		<th>Active</th>
		<th>&nbsp;</th>
	</tr>
	<% @users.each do |u| %>
		<tr class="<%= cycle('even', 'odd') %>">
			<td>
				<%= u %>
			</td>
			<td>
				<%= u.email %>
			</td>
			<td>
				<%= u.fund %>
			</td>
			<td class="center">
				<%= raw u.show_role %>
			</td>
			<td class="center">
				<%= boolean_icon(u.active) %>
			</td>
			<td>
				<%= link_to 'edit', edit_admin_user_path(u.id) %>
			</td>
		</tr>
	<% end %>
</table>

app/views/admin/users/new.html.erb
<%= form_for @user, :url => admin_users_path do |f| -%>
	<%= render :partial => 'form', :object => f %>
<% end -%>